name: Test

on:
  push:
    branches:
      - main
    paths:
      - pii_anonymizer
      - pyproject.toml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - name: Unit Test
        run: make test
      - name: E2E Test
        run: make e2e
